import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Clientshell from "./Clientshell";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "@/components/ui/sonner";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sora.variable} antialiased`}>
        <NextTopLoader color="#00943f" height={4} showSpinner={false} />
        <Clientshell>{children}</Clientshell>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
